# Generated by Django 6.1 on 2026-08-14 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquetipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('palabra_clave', models.CharField(max_length=100)),
                ('genero_articulo', models.CharField(choices=[('M', 'Masculino (El)'), ('F', 'Femenino (La)')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='DescripcionArquetipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=1)),
                ('texto', models.TextField()),
                ('arquetipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descripciones', to='test_arquetipos.arquetipo')),
            ],
        ),
        migrations.CreateModel(
            name='PersonajeCrush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango_edad', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=150)),
                ('arquetipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crushes', to='test_arquetipos.arquetipo')),
            ],
        ),
        migrations.CreateModel(
            name='PersonajeFamoso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango_edad', models.CharField(choices=[('< 20', 'Menor de 20'), ('20 a 30', '20 a 30 años'), ('31 a 40', '31 a 40 años'), ('41 a 50', '41 a 50 años'), ('> 50', 'Mayor de 50')], max_length=50)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('nombre', models.CharField(max_length=150)),
                ('arquetipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='famosos', to='test_arquetipos.arquetipo')),
            ],
        ),
        migrations.CreateModel(
            name='PersonajeMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango_edad', models.CharField(choices=[('< 20', 'Menor de 20'), ('20 a 30', '20 a 30 años'), ('31 a 40', '31 a 40 años'), ('41 a 50', '41 a 50 años'), ('> 50', 'Mayor de 50')], max_length=50)),
                ('genero_musical', models.CharField(choices=[('Rock', 'Rock'), ('Urbano/Pop', 'Urbano/Pop'), ('Cumbia/Cuarteto', 'Cumbia/Cuarteto'), ('Electronica', 'Electrónica'), ('Folclore', 'Folclore')], max_length=50)),
                ('cancion_identidad', models.CharField(blank=True, max_length=200, null=True)),
                ('arquetipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_base', to='test_arquetipos.arquetipo', verbose_name='Tu Arquetipo')),
                ('arquetipo_match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='es_match_de', to='test_arquetipos.arquetipo', verbose_name='Hace match con (Complementario)')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('ESCALA', 'Escala 1 a 5'), ('VISUAL', 'Imagen / Visual')], default='ESCALA', max_length=10)),
                ('multiplicador', models.IntegerField(default=1)),
                ('arquetipo_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='test_arquetipos.arquetipo')),
            ],
        ),
        migrations.CreateModel(
            name='SesionJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=50)),
                ('genero', models.CharField(blank=True, max_length=10, null=True)),
                ('musica', models.CharField(max_length=50)),
                ('cancion_resultado', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('arquetipo_resultado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_arquetipos.arquetipo')),
            ],
        ),
    ]
